export default [
  { lable: "暂存", className: "a-yellow-color" },
  { lable: "已放弃", className: "a-red-color" },
  { lable: "已约评审会", className: "b-blue-color" },
  { lable: "评审中", className: "a-yellow-color" },
  { lable: "已评审", className: "a-green-color" },
  { lable: "审批中", className: "a-yellow-color" },
  { lable: "重谈", className: "a-yellow-color" },
  { lable: "不合作", className: "a-red-color" },
  { lable: "待上传加工协议", className: "b-blue-color" },
  { lable: "待评估风险", className: "b-blue-color" },
  { lable: "风险评审中", className: "a-yellow-color" },
  { lable: "待修改加工协议", className: "b-blue-color" },
  { lable: "待与客户沟通", className: "b-blue-color" },
  { lable: "待回签加工协议", className: "b-blue-color" },
  { lable: "合格", className: "a-green-color" },
  { lable: "黑名单", className: "a-red-color" },
] as const;