FROM harbor-rongshu-saas.com/front/nginx:0.002

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /usr/share/nginx/html

RUN rm -frv /etc/nginx/conf.d/*
RUN rm -frv /usr/share/nginx/html/*

COPY default.conf /etc/nginx/conf.d

COPY dist/ ./

EXPOSE 80
