###
POST http://192.168.8.136:7777/api/customer/customer/pageInfo HTTP/1.1
Content-Type: application/json
token: 92f5324d-9bfe-4b35-abd3-0e36e3c84a68

{"pageNum":1,"pageSize":20,"userId":"16281353481807069"}
###
post http://192.168.8.133:8090/customer/pageInfo  HTTP/1.1
Content-Type: application/json

{
  "pageNum": 2,
  "pageSize": 2
}

###
post http://192.168.8.133:8090/product/list  HTTP/1.1
Content-Type: application/json

{
  "searchValue": "电"
}


###
GET http://192.168.28.51:30300/api/upms/auth/fordingdingCode?code=6c34bf4923313a4086ec2173a1d94b65 HTTP/1.1

###
GET http://192.168.8.136:7778/api/producer/prepareMaterials/getParams/1 HTTP/1.1
token: 92f5324d-9bfe-4b35-abd3-0e36e3c84a68

###
GET http://192.168.28.51:30090/dingding_tools/getToolsMan HTTP/1.1

###
POST http://192.168.28.51:30300/api/saas/common/flowable/pageInfo HTTP/1.1
Content-Type: application/json

{}

### 未读总记录数
GET http://192.168.12.150:8095/workTask/unReadStatus HTTP/1.1